---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-download-site-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-download-site
  template:
    metadata:
      labels:
        app: nginx-download-site
    spec:
      containers:
      - name: nginx-download-site
        image: petrosg8/nginx-download-site:latest
        env:
        - name: SITE_URL
          value: "http://csd.uoc.gr"
        # - name: HANDLER_PATH_PREFIX
        #   value: /csd
        # - name: RENDER_PATH_PREFIX
        #   value: /csd
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-download-site-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP       
  selector:
    app: nginx-download-site
