apiVersion: v1
kind: ServiceAccount
metadata:
  name: greeting-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: greeting-controller
rules:
  - apiGroups: ["hy548.csd.uoc.gr"]
    resources: ["greetings"]
    verbs: ["get","list","watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: [""]
    resources: ["services","pods"]
    verbs: ["get","list","watch","create","update","patch","delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: greeting-controller
subjects:
  - kind: ServiceAccount
    name: greeting-controller
roleRef:
  kind: Role
  name: greeting-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-controller
  template:
    metadata:
      labels: {app: greeting-controller}
    spec:
      serviceAccountName: greeting-controller
      containers:
        - name: controller
          image: petrosg8/greeting-controller:latest
          env:
            - name: WATCH_NAMESPACE              
              valueFrom:
                fieldRef: {fieldPath: metadata.namespace}
            - name: GREETING_CRD_GROUP           
              value: hy548.csd.uoc.gr
            - name: GREETING_CRD_VERSION
              value: v1
