apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fruits.hy548.csd.uoc.gr          
spec:
  group: hy548.csd.uoc.gr
  scope: Namespaced                      
  names:
    plural: fruits
    singular: fruit
    kind: Fruit
    shortNames:
      - fr                               
  versions:
    - name: v1
      served: true
      storage: true
      schema:                           
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["origin", "count", "grams"]
              properties:
                origin:
                  type: string
                  description: Where the fruit comes from
                count:
                  type: integer
                  minimum: 0
                  description: Number of pieces
                grams:
                  type: integer
                  minimum: 0
                  description: Total weight in grams
            status:                      
              type: object
      subresources:
        status: {}                       
