###############################################################################
# Namespace
###############################################################################
apiVersion: v1
kind: Namespace
metadata:
  name: custom-label-injector
  labels:
    app: custom-label-injector
---
###############################################################################
# TLS issuer and certificate (cert-manager)
###############################################################################
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: custom-label-injector
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-server-cert
  namespace: custom-label-injector
spec:
  secretName: webhook-server-cert          
  duration: 87600h                         
  commonName: custom-label-webhook.custom-label-injector.svc
  dnsNames:
    - custom-label-webhook.custom-label-injector.svc
    - custom-label-webhook.custom-label-injector.svc.cluster.local
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned
---
###############################################################################
# ServiceAccount, Role, RoleBinding
###############################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-sa
  namespace: custom-label-injector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webhook
  namespace: custom-label-injector
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webhook
  namespace: custom-label-injector
subjects:
  - kind: ServiceAccount
    name: webhook-sa
roleRef:
  kind: Role
  name: webhook
  apiGroup: rbac.authorization.k8s.io
---
###############################################################################
# Service (cluster-internal HTTPS endpoint)
###############################################################################
apiVersion: v1
kind: Service
metadata:
  name: custom-label-webhook
  namespace: custom-label-injector
  labels:
    app: custom-label-webhook
spec:
  type: ClusterIP
  selector:
    app: custom-label-webhook
  ports:
    - name: https
      port: 443
      targetPort: 8000                     
---
###############################################################################
# Deployment 
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-label-webhook
  namespace: custom-label-injector
  labels:
    app: custom-label-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-label-webhook
  template:
    metadata:
      labels:
        app: custom-label-webhook
    spec:
      serviceAccountName: webhook-sa
      volumes:
        - name: tls
          secret:
            secretName: webhook-server-cert
      containers:
        - name: webhook
          image: petrosg8/custom-label-webhook:latest   
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:  
            - name: CUSTOM_LABEL
              value: custom-label
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
---
###############################################################################
# MutatingWebhookConfiguration 
###############################################################################
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: custom-label-injector
  annotations:
    cert-manager.io/inject-ca-from: custom-label-injector/webhook-server-cert
webhooks:
  - name: label.injector.hy548.csd.uoc.gr
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: custom-label-webhook
        namespace: custom-label-injector
        path: /mutate
        port: 443
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        custom-label-injector: enabled
